const meta = {
  title: "Chameleo Kidz Academy",
  description: "Singapore dance school",
};

const headerData = {
  content:
    "We are a dance school in Singapore with a noble aim to provide fun and progressive activities for your child, and to nurture talents.",
  footer: "Are you considering to enhance your school’s offerings?",
};

const aboutUsData = {
  points: [
    {
      title: "MISSION",
      description:
        "To provide children an outlet to develop their capabilities holistically by setting the right environment through our interactions and gestures.",
      src: "/aboutUs/mission.svg",
    },
    {
      title: "VISION",
      description:
        "We strive to be the leading academy in which we bring out the unique potential of each child through safe and nurturing mentorship.",
      src: "/aboutUs/vision.svg",
    },
    {
      title: "PHILOSOPHY",
      description:
        "In line with Lev Vygotsky's sociocultural theory, we believe that a child's learning revolves around the social interaction in his environment.\n\nChildren are actively constructing knowledge through social interaction, objects and the surrounding environment around them.\n\nThrough direct interaction with the dance instructors and indirectly through the social cues exhibited during lessons.",
      src: "/aboutUs/philosophy.svg",
    },
  ],
};

const ourClassesData = {
  header:
    "Our programmes are conducted by highly qualified instructors who are experienced with children and parents.",
  points: [
    {
      title: "Hip-Hop",
      description:
        "Hip-Hop dance at its core is in no way, shape or form a mere dance routine. And so, is about being able to express yourself through movement to the music.",
      src: "/ourClasses/hipHop.svg",
      background: "#3e88ce",
      foreground: "#b4dbff",
      isPopular: true,
    },
    {
      title: "Tap Dance",
      description:
        "The essence of Tap dancing is about creating rhythmic music through dance. Rhythm is generated by tapping and sliding the feet in variations.",
      src: "/ourClasses/tapDance.svg",
      background: "#e1a32c",
      foreground: "#ffecc8",
      isPopular: false,
    },
    {
      title: "Jazz",
      description:
        "Jazz dancing is a form that showcases a dancer's originality - interpreting and executing moves and steps in their own way. This type of dance ranges from the isolation of certain body parts to the movement of the entire body with the accents of musical rhythms.",
      src: "/ourClasses/jazz.svg",
      background: "#58a645",
      foreground: "#ddfad6",
      isPopular: false,
    },
  ],
  footer: "Looking to diversify your school's curriculum?",
};

const reviewsData = {
  reviews: [
    {
      name: "Mun Weilin",
      occupation:
        "Assistant Head (The GRIT Project) Lakeside Family Services (Nanyang Centre)",
      review:
        "The instructor was prepared well for the lessons and at the same time, was very quick to adapt to meet the needs of the students. He was unfazed by any challenges! He was also able to cater to the different abilities of the youths and explain steps in a clear and engaging manner. He even came earlier/stayed later to answer questions/teach extra steps for those interested.",
    },
    {
      name: "Xin Yi",
      occupation: "Parent of Zayne",
      review:
        "It was a short 45 mins lesson, but just nice for the attention span of a 6y/o. The moves are also relatively easy for him to follow. He was a little shy at the beginning but the teacher was patient and encouraging. Kudos to the team!",
    },
    {
      name: "Lee Ling",
      occupation: "Parent of Megan",
      review:
        "She looked forward to attending the trial class after knowing that a dance trial was arranged for her. It was a wonderful trial, she enjoyed it, and also had a great fun time with Katie, who joined in halfway through the class. Thanks the wonderful teams that encouraged and offer Katie to join in.",
    },
    {
      name: "Vivian",
      occupation: "Parent of Kayla",
      review:
        "Didn’t expect she would enjoy dance class so much like this. It was her first try of Hip Hop dance and she’s totally hooked! The instructor and staff were so fun, friendly & encouraging, making Kayla feel comfortable and eager to try more choreography. She really had a great time! ",
    },
    {
      name: "Joy Wong",
      occupation: "Parent of Eden",
      review:
        "Eden usually needs some time to warm up but I admire the patience that the team has with him. I saw them trying many ways to encourage him. And in the end turns out he enjoyed and when he comes home he ask me whether he danced well 🤣 Truly a fun experience for us! ",
    },
    {
      name: "Xiao Ting",
      occupation: "Parent of Quinceton",
      review:
        "Quinceton 1st Hip Hop dance lesson. The lesson was fun and engaging. Quinceton had a tremendous amount of fun during the lesson and was able to perform a short dance under the guidance of the instructor at the end of the session.",
    },
  ],
};

const socials = {
  contact: "+65 8833 2669",
  email: "info@chameleokidz.com",
  whatsApp: "https://wa.me/+6588332669",
  facebook: "https://www.facebook.com/ChameleoKidz?mibextid=ZbWKwL",
  instagram: "https://www.instagram.com/chameleokidz/?igsh=bmllY2Z5c2lsd3E5",
};

export { meta, headerData, aboutUsData, ourClassesData, reviewsData, socials };
